### PR TITLE
Issue #7 - Skin/theme PASS UI with JHU's color and logo

### PR DESCRIPTION
**Pull request by jabrah**
Changes logo and favicon and starts applying JHU style guidelines to PASS

### CODE REVIEW

**Comment by htpvu** [comment]
Issues found with Submission details side bar not visible.

To see this: 
- Click on 'view grants"
- click on a grant's Award Number
- from grant details page, click on "new submission"
- click "next" on the modal popup
- then click "save and continue"
- observe the side bar.

**Comment by htpvu** [comment]
screen shot 2017-12-07 at 10 12 06 am

**Comment by birkland** [comment]
@hvu @jabrah The contents of the navigation sidebar are in `app/templates/components/submission-nav.hbs`.  Basically it's just 

    <nav>
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                {{#link-to "submission.show.index" submission class="nav-link" }}
                    Overview
                {{/link-to}}
            </li>
            <li class="nav-item">
                {{#link-to "submission.show.funding" submission class="nav-link" }}
                    Funders
                {{/link-to}}
            </li>
           ... [repeat for all categories]
        </ul>
    </nav>

**Comment by htpvu** [comment]
@birkland the content is all there. it's just the with the recent styling John did the text and background have the same color, so the text didn't show up. Just a color change - i believe.

**Comment by birkland** [comment]
@htpvu  Indeed.   I was just pointing out where to find the html and (especially) the relevant classes for styling purposes, like `nav-item`, `nav-link`, etc.  The selected one is `active`, I think

**Pull request merged**
